Deploy easyrsa as a prerequisite for restore
Otherwise the subsequent restore action will fail with:
FileNotFoundError: [Errno 2] No such file or directory:
'/var/snap/etcd/common/etcd.conf.yml'
Because "new-etcd" is not bootstrapped yet since no CA is available.

Naming easyrsa as "new-easyrsa" is necessary since new-etcd will be
stuck if an existing easyrsa is used. The issue is tracked as
LP: #1835056 (https://launchpad.net/bugs/1835056)